#!/bin/bash

dir=$1;
arch=$3;
[[ "$arch" = "i386" ]] && arch="386"
[[ "$arch" = "armhf" ]] && arch="arm"

export GOPATH=`mktemp -d`;
export GOARCH=$arch;
unset GOBIN

go get github.com/penguinpowernz/go-ian;
go get github.com/penguinpowernz/go-ian/...;
go build -o $dir/usr/bin/ian github.com/penguinpowernz/go-ian/cmd/ian;

exit 0;
